### ISSUE TITLE
Duplicate grants check missing from 360Giving CoVE

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#569] opened 2017-02-06 18:25 UTC
This was removed when we removed the 'Grants' vs 'Grant IDs' from Review. We were going to add an Additional Check for it, but this proved to be difficult. We should re-instate the original approach, potentially with new copy to help explain it

**Comment by Bjwebb** [comment] 2017-02-07 16:09
I'm not sure this makes sense - those numbers will be the same for all spreadsheet publishers. Rather for speradsheets, duplicates are seen only by flatten-tool.

**Comment by robredpath** [comment] 2017-02-07 18:16
Quite possibly I've misunderstood what's missing - Edafe said "We've also lost the check for duplicate grants which can seen in the live cove.".

**Comment by robredpath** [comment] 2017-02-28 11:41
This is being discussed in internal issue #8253 as the discussion involves pre-publication data

**Comment by robredpath** [comment] 2017-04-10 10:18
After discussion, we've realised that what's needed here is some numbers from the data pre-merge that aren't currently captured - although there is a loss of function between 'old' CoVE and 'new' CoVE, the feature didn't actually do what was assumed and doesn't meet the need that we thought it did. So, I've classed this as a non-blocking enhancement rather than a bug. I believe @Bjwebb and @ekoner are discussing this in person today as well.

**Comment by kindly** [comment] 2017-09-08 15:30
There is an possibility to add some statistic generation to flattentool, which would not be that difficult todo. 

The issue is what statistics we would need to give a useful error message to the end users.

The main problem is that it is impossible for flattentool to detect real duplicate ids vs ids that are intended to be merged.

The statistics we could produce fairly simply are:
- Actual data rows per sheet in a spreadsheet/csv (this would be before merging)
- How many merges happen per sheet or overall.
- How many warnings happen per sheet due to conflicts in merging.
- Unique grant ids per sheet.
- Duplicate grant ids per sheet.

The information we could produce with much difficulty:

- How many rows are exact duplicates (i.e no merge warnings but probably mistakes).
- How many rows with some duplicate information excluding ids that do not cause merge warning (i.e one row just has more information that another but agree on data they include).
- Finding out what is the "main" sheet (i.e the grants sheet) so we can look for duplicate grant ids in that sheet.

My conclusion to this is that even with flattentool help is would be fairly tricky to determine is somebody put in a duplicate grant id by mistake or by intention.

We could do something like:

- If there exists a sheet called "Grants" and it has more rows in than unique grant ids then give a warning to the end user.
- Produce "grant ids"/"duplicate grant ids" per sheet rather than for all the data. 
- Just add to the results rows per sheet information and let the user see spot if there any duplicates themselves.

**Comment by stevieflow** [comment] 2017-10-11 13:15
@kindly and I discussed this - we landed on this feedback for spreadsheet input:

- number of populated rows per sheet (not counting header)
- unique identifiers per sheet

**Closed** 2022-07-11 12:41 UTC
Labels: enhancement, 360Giving
