### ISSUE TITLE
OCDS Validator: 500 error when validating bids extension

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#823] opened 2017-08-31 11:23 UTC
Trying to validate a file with the bids extension declared in the extensions array results in a [500 error](http://standard.open-contracting.org/validator/data/87e6e6ac-1578-45ad-9ee2-96801cd829b7)

Originally noted on [this file](https://gist.github.com/duncandewhurst/459078c48b924c0f8df5d72b1206d28d) from OpenNWT.

Reproduced when trying to validate the following data (taken from the [extensions](http://standard.open-contracting.org/latest/en/extensions/#using-extensions) section of the docs)

```json
{
    "extensions":["https://raw.githubusercontent.com/open-contracting/ocds_bid_extension/v1.1/extension.json"],
    "releases":[]
}
```

**Comment by edugomez** [comment] 2017-08-31 11:55
The problem seems to be this 
```jsonref.JsonRefError: ("Unresolvable JSON pointer: '/definitions/RequirementResponse'", OrderedDict([('$ref', '#/definitions/RequirementResponse')]))```

The definition of ```RequirementResponse```is in [ocds_requirements_extension](https://github.com/open-contracting/ocds_requirements_extension).

So adding _"https://raw.githubusercontent.com/open-contracting/ocds_requirements_extension/master/extension.json"_ to the extension array fixes the problem.

**Comment by edugomez** [comment] 2017-08-31 12:01
BTW, good reminder that (atm) we deal badly with extension dependencies.

**Comment by edugomez** [comment] 2017-08-31 12:11
Relate to https://github.com/OpenDataServices/cove/issues/809

**Comment by duncandewhurst** [comment] 2017-08-31 13:01
thanks @edugomez - since this is a community extension I think it's fine to use `master`, the `ppp` release was created so we have fixed version for the ppp profile (to avoid breaking translations)

@dwasyl - see https://github.com/OpenDataServices/cove/issues/823#issuecomment-326273195 for the solution to the 500 error you are getting

**Comment by edugomez** [comment] 2017-08-31 13:32
Closing this one, but the issue of dealing more gracefully with missing JSON pointers for jsonref is still outstanding at https://github.com/OpenDataServices/cove/issues/809

**Closed by edugomez** 2017-08-31 13:32 UTC
Labels: bug, OCDS-extensions

**Comment by edugomez** [comment] 2017-09-01 15:41
FYI,  the problem is related to the discussion in this issue in OCDS extension registry https://github.com/open-contracting/extension_registry/issues/56, also in this one https://github.com/open-contracting/extension_registry/issues/47
