### ISSUE TITLE
Cache data showing when it should not?

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#163] opened 2015-11-30 12:16 UTC
![screenshot from 2015-11-30 12 16 59](https://cloud.githubusercontent.com/assets/185467/11471320/6c1562fa-975c-11e5-9938-4d457b44aa4c.png)
Please would you investigate this for me?

1) I go to  http://dev.cove.opendataservices.coop/360/
2) I paste in the following URL: http://zing.org.uk/open/grants.csv
This URL results in a 404 (on the web), but on submission I see:
http://dev.cove.opendataservices.coop/360/data/05554af8-e54e-4bba-96af-e6089237f253

I suspect this URL' worked' in the last 7 days, and that I'm seeing an error based on the data from that URL back then. 

Instead it should be failing because there is no data to grab from there in the first place.

**Comment by Bjwebb** [comment] 2015-11-30 12:38
@caprenter I see a CSV file locally too.

**Comment by caprenter** [comment] 2015-11-30 12:40
Does your local file contain 'zing' data?

**Comment by Bjwebb** [comment] 2015-11-30 12:44
@caprenter Yes.

**Comment by Bjwebb** [comment] 2015-11-30 12:49
Looks like they were in the middle of changing their DNS. Closing this issue as I don't think Cove was in the wrong here (although it could handle 404s better, see https://github.com/OpenDataServices/cove/issues/162 )

**Comment by timgdavies** [comment] 2015-12-14 09:55
I'm still getting the same experience with Zing data. I can download a local copy, but if I try with CoVE I get a 404 page...

**Comment by Bjwebb** [comment] 2015-12-14 10:00
@timgdavies Odd that it still persists. I still think this is an issue with Zing's DNS (and that being cached on the DNS servers people use, but not on CoVE) - and not an issue with CoVE. In particular, I can reproduce the 404 with curl on our servers (but the same command works locally).

**Comment by timgdavies** [comment] 2015-12-14 10:05
Odd. Ok - well, definitely worth us getting the 404 handling in soon so that we don't end up trying to analyse HTML 404 pages a CSV in cases like this.

**Comment by caprenter** [comment] 2015-12-14 10:06
which version of cove and which zing link?

I can get both cove. and dev.cove to 'work' with http://zing.org.uk/open/grants.csv

**Comment by timgdavies** [comment] 2015-12-14 10:07
http://zing.org.uk/open/grants.csv

It 'works', but if you inspect the CSV or JSON file created, it has grabbed the HTML of a 404 page.

Example here http://dev.cove.opendataservices.coop/360/data/174b9c15-f04f-4d5e-a300-77d5ce4a2676

**Comment by Bjwebb** [comment] 2015-12-14 10:07
Yep.

Actually, just taken a look a the output of `dig zing.org.uk` and it looks like that has two different responses - so it is a DNS issue, but it's not a propogation/caching issue.  Therefore, everything will randomly switch between the working and not-working IP address...

**Comment by Bjwebb** [comment] 2015-12-15 18:02
I've raised the issue with Zing.

**Closed by Bjwebb** 2015-12-15 18:02 UTC
