### ISSUE TITLE
Improve OCDS record oneOf validation message

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#1015] opened 2018-04-26 13:20 UTC
From https://github.com/OpenDataServices/cove/issues/951

**Comment by jpmckinney** [comment] 2018-04-27 07:06
Potential duplicate of #895

**Comment by robredpath** [comment] 2018-05-14 09:45
Agreed @jpmckinney , closing.

**Closed by robredpath** 2018-05-14 09:45 UTC
Labels: OCDS

**Comment by duncandewhurst** [comment] 2019-07-23 09:08
![](https://github.trello.services/images/mini-trello-icon.png) [Data Review Tool: Correct reporting of giant blocks of JSON](https://trello.com/c/dXzzBjKM/48-data-review-tool-correct-reporting-of-giant-blocks-of-json)
