### ISSUE TITLE
Unintelligible IATI CoVE Error - something to do with openpyxl

### ISSUE THREAD

**Issue by rory09** [OpenDataServices/cove#977] opened 2018-02-20 10:16 UTC
![image](https://user-images.githubusercontent.com/7805169/36418275-471f17fc-1626-11e8-8068-2633be1acb67.png)

This error came up when working with client data which is as yet not public. I'll send a copy internally for so it can be reproduced.

See [sentry](https://sentry.io/open-data-services/cove/issues/470783528/) ([dev](https://sentry.io/open-data-services/cove-dev/issues/468854310/)) for the traceback.

**Comment by rory09** [comment] 2018-02-20 11:07
I've fixed this issue by creating a new tab in the conversion sheet, copying all of the values over with shift+ctrl+p (so as to reserve the values only), and then deleting the original sheet. 

As such, this issue isn't urgent anymore, but it would be good to understand what the issue was when someone has time to look at it.

**Comment by Bjwebb** [comment] 2018-02-20 11:21
This is a bug in openpyxl itself.
Here's a deploy with openpyxl downgraded: http://downgrade-openpyxl.dev.cove.opendataservices.coop/ (Note: this reintroduces the date error https://github.com/OpenDataServices/cove/issues/954)

I'll see if I can make a reproducing example without client data in it, and report the issue upstream.

**Comment by Bjwebb** [comment] 2018-02-22 16:46
I've reported this upstream now https://bitbucket.org/openpyxl/openpyxl/issues/981/can-not-open-file-due-to-typeerror
Closing this issue until we run into it again.

**Comment by Bjwebb** [comment] 2018-02-28 09:40
@rory09 Apparently this is LibreOffice's fault https://bitbucket.org/openpyxl/openpyxl/issues/981/can-not-open-file-due-to-typeerror

No action here, just re-open this issue if it crops up again.

**Comment by andylolz** [comment] 2018-03-23 15:18
Similar error from a file that passed through OpenOffice:
![screen shot 2018-03-23 at 15 15 48](https://user-images.githubusercontent.com/464193/37837462-2a30ce48-2ead-11e8-9150-81c5d7d7f9f3.png)

**Comment by Bjwebb** [comment] 2018-04-24 14:47
This has cropped up again. Internal links https://opendataservices.plan.io/issues/14527 https://sentry.io/open-data-services/cove/issues/470783528/events/18693663558/

**Comment by Bjwebb** [comment] 2019-01-28 08:09
@rory09 Is this still an issue?

**Comment by rory09** [comment] 2019-01-28 15:40
Yup - still can't open an a file with a pivot table in it, even if it's commented out. See this error: http://iati.cove.opendataservices.coop/data/41910ab4-8278-4972-862f-b28657ceeeb0

As far as I can remember, this is entirely down to openpyxl's new version not being able to open the file if there's a pivot table (certainly one created in google sheets and then downloaded as .xlsx

**Comment by rory09** [comment] 2019-02-05 09:52
@Bjwebb here is an example file https://docs.google.com/spreadsheets/d/1p-6zgIEXmLWSixDuOH_p6xhnPC64pri-acu5sL8I-OE/export?format=xlsx

**Comment by Bjwebb** [comment] 2019-02-07 05:47
I've created a small simple sample file that reproduces this, and reported that on the openpyxl issue tracker https://bitbucket.org/openpyxl/openpyxl/issues/1175/google-sheets-pivot-table-causes-openpyxl

**Comment by rory09** [comment] 2019-02-07 09:07
Thanks Ben!

**Comment by Bjwebb** [comment] 2019-02-14 04:45
Looks like my sample file has a different error to the real example file.

Currently that real file isn't public, so I can't share it. Is this deliberate, or is it meant to be public?

**Comment by rory09** [comment] 2019-02-27 08:42
I've made it public (to view) for now. I think we didn't make the broken examples public because there was no need to until now. Let me know if you need anything else. Thanks!

**Comment by Bjwebb** [comment] 2019-03-01 08:19
Thanks, I've made another bug report https://bitbucket.org/openpyxl/openpyxl/issues/1213/another-google-sheets-pivot-table-crash

It looks like the problem might be Google Docs not complying with the XLSX standard.

Even if this doesn't get fixed (by openpyxl or google), I think there is a way we can work around this - monkeypatching openpyxl to disable pivot table support.

**Comment by Bjwebb** [comment] 2019-03-07 09:42
Looks like this has been fixed upstream. Seems like it was an error in openpyxl after all.

Here's a demo instance with the latest openpyxl release - http://977-openpyxl-trunk.dev.cove.opendataservices.coop/

Looks like there might be other issues with flatten-tool and the latest openpyxl - https://github.com/OpenDataServices/flatten-tool/issues/287 - so that will need to be fixed before this goes live.

**Closed** 2019-03-26 03:42 UTC
Labels: IATI, bug
